# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 547)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.currentKeyLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentKeyLabel.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.currentKeyLabel.setObjectName("currentKeyLabel")
        self.runServerButton = QtWidgets.QPushButton(self.centralwidget)
        self.runServerButton.setGeometry(QtCore.QRect(880, 45, 121, 28))
        self.runServerButton.setObjectName("runServerButton")
        self.rekeyButton = QtWidgets.QPushButton(self.centralwidget)
        self.rekeyButton.setGeometry(QtCore.QRect(880, 80, 121, 28))
        self.rekeyButton.setObjectName("rekeyButton")
        self.commandPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.commandPlainTextEdit.setGeometry(QtCore.QRect(130, 10, 871, 31))
        self.commandPlainTextEdit.setObjectName("commandPlainTextEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(10, 10, 111, 28))
        self.sendButton.setObjectName("sendButton")
        self.prevKeyLabel = QtWidgets.QLabel(self.centralwidget)
        self.prevKeyLabel.setGeometry(QtCore.QRect(10, 50, 101, 16))
        self.prevKeyLabel.setObjectName("prevKeyLabel")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 160, 991, 331))
        self.textBrowser.setObjectName("textBrowser")
        self.prevKeyEmptyLabel = QtWidgets.QLabel(self.centralwidget)
        self.prevKeyEmptyLabel.setGeometry(QtCore.QRect(90, 50, 781, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.prevKeyEmptyLabel.setFont(font)
        self.prevKeyEmptyLabel.setText("")
        self.prevKeyEmptyLabel.setObjectName("prevKeyEmptyLabel")
        self.currentKeyEmptyLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentKeyEmptyLabel.setGeometry(QtCore.QRect(90, 70, 781, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.currentKeyEmptyLabel.setFont(font)
        self.currentKeyEmptyLabel.setText("")
        self.currentKeyEmptyLabel.setObjectName("currentKeyEmptyLabel")
        self.aesIVLabel = QtWidgets.QLabel(self.centralwidget)
        self.aesIVLabel.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.aesIVLabel.setObjectName("aesIVLabel")
        self.aesEncryptLabel = QtWidgets.QLabel(self.centralwidget)
        self.aesEncryptLabel.setGeometry(QtCore.QRect(10, 110, 101, 16))
        self.aesEncryptLabel.setObjectName("aesEncryptLabel")
        self.shaLabel = QtWidgets.QLabel(self.centralwidget)
        self.shaLabel.setGeometry(QtCore.QRect(10, 130, 101, 16))
        self.shaLabel.setObjectName("shaLabel")
        self.aesIVEmptyLabel = QtWidgets.QLabel(self.centralwidget)
        self.aesIVEmptyLabel.setGeometry(QtCore.QRect(120, 90, 691, 20))
        self.aesIVEmptyLabel.setText("")
        self.aesIVEmptyLabel.setObjectName("aesIVEmptyLabel")
        self.aesEncryptEmpytLabel = QtWidgets.QLabel(self.centralwidget)
        self.aesEncryptEmpytLabel.setGeometry(QtCore.QRect(120, 110, 691, 20))
        self.aesEncryptEmpytLabel.setText("")
        self.aesEncryptEmpytLabel.setObjectName("aesEncryptEmpytLabel")
        self.shaEmptyLabel = QtWidgets.QLabel(self.centralwidget)
        self.shaEmptyLabel.setGeometry(QtCore.QRect(120, 130, 811, 20))
        self.shaEmptyLabel.setText("")
        self.shaEmptyLabel.setObjectName("shaEmptyLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Server"))
        self.currentKeyLabel.setText(_translate("MainWindow", "Current Key:"))
        self.runServerButton.setText(_translate("MainWindow", "Run Server"))
        self.rekeyButton.setText(_translate("MainWindow", "Rekey"))
        self.sendButton.setText(_translate("MainWindow", "Send Data"))
        self.prevKeyLabel.setText(_translate("MainWindow", "Previous Key:"))
        self.aesIVLabel.setText(_translate("MainWindow", "AES IV:"))
        self.aesEncryptLabel.setText(_translate("MainWindow", "AES Encrypt Key:"))
        self.shaLabel.setText(_translate("MainWindow", "SHA256 Hash:"))

